Created DailyAlertChecker method
infoshareacademy/JJDZR13-JAVAers pull request #5
Opened 2024-02-02 20:19 UTC by marek-posturzynski

2024-02-07 18:50 UTC, TomaszOdwald requested changes

2024-02-07 18:50 UTC, TomaszOdwald commented on src/main/java/pl/isa/javaers/DailyAlertChecker.java
> +                    fileWriter.close();                     //zamkniecie pliku dla szybkości działania programu
Zamykanie pliku powinno być w bloku finally, ewentualnie poprzez zapis `try (FileWriter fileWriter = new FileWriter(dailyAlertFile, true)) {`.

2024-02-07 18:50 UTC, TomaszOdwald commented on src/main/java/pl/isa/javaers/DailyAlertChecker.java
> +        if (isAlertConditionFulfilled) {
Po co ten if, jeśli jest zawsze true? :)

2024-02-07 18:50 UTC, TomaszOdwald commented on src/main/java/pl/isa/javaers/DailyAlertChecker.java
> +//    private Date actualDate = Date.valueOf(LocalDate.now());
Nieużywane to usuwamy :)

2024-02-08 11:48 UTC, marek-posturzynski commented on src/main/java/pl/isa/javaers/DailyAlertChecker.java
> +        if (isAlertConditionFulfilled) {
Ok, myślę że zrobienie w polach tej klasy pola isAlertConditionFulfilled jako "static" załatwia sprawę.

2024-02-08 16:15 UTC, marek-posturzynski commented on src/main/java/pl/isa/javaers/DailyAlertChecker.java
> +                    fileWriter.close();                     //zamkniecie pliku dla szybkości działania programu
z tym nie mogę sobie poradzić

2024-02-09 21:21 UTC, merged